Compiled from "AbstractItemStack.java"
public interface io.lumine.mythic.api.adapters.AbstractItemStack {
  public abstract java.lang.String getName();
  public abstract net.kyori.adventure.text.Component name();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack setName(java.lang.String);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack name(net.kyori.adventure.text.Component);
  public abstract java.util.Collection<java.lang.String> getLore();
  public abstract java.util.Collection<net.kyori.adventure.text.Component> lore();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack setLore(java.util.List<java.lang.String>);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack lore(java.util.List<net.kyori.adventure.text.Component>);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack loreText(java.util.List<java.lang.String>);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack clearLore();
  public abstract int getAmount();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack amount(int);
  public abstract int getData();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack data(int);
  public abstract boolean isBreakable();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack breakable(boolean);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack hideAll();
  public default io.lumine.mythic.api.adapters.AbstractItemStack flags(io.lumine.mythic.api.adapters.AbstractItemFlag...);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack flags(java.util.Collection<io.lumine.mythic.api.adapters.AbstractItemFlag>);
  public abstract int getRepairCost();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack repairCost(int);
  public abstract int getMaxStackSize();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack maxStackSize(int);
  public default io.lumine.mythic.api.adapters.AbstractItemStack unstackable();
  public abstract int getModelData();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack modelData(int);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack addAttributeModifier(io.lumine.mythic.api.adapters.AbstractAttributeModifier);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack skullOwner(java.lang.String);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack skullOwner(java.lang.String, java.util.UUID);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack skullTexture(java.lang.String);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack skullTexture(java.net.URI);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack skullTextureId(java.lang.String);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack enchant(org.bukkit.enchantments.Enchantment, int);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack removeEnchant(org.bukkit.enchantments.Enchantment);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack enchantmentGlow(boolean);
  public abstract int getDurability();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack durability(int);
  public abstract int getMaxDurability();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack maxDurability(int);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack canPlaceOn(java.util.Collection<org.bukkit.Material>);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack canBreak(java.util.Collection<org.bukkit.Material>);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack potionEffect(org.bukkit.potion.PotionEffectType, int, int);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack color(int, int, int);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack color(io.lumine.mythic.bukkit.utils.serialize.Chroma);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack color(java.lang.String);
  public abstract io.lumine.mythic.core.utils.jnbt.CompoundTag getCustomData();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyBannerComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemBannerComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyFoodComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemFoodComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyConsumableComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemConsumableComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyPotionComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemPotionComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyEquippableComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemEquippableComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyUseCooldownComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemUseCooldownComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyToolComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemToolComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyTooltipComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemTooltipComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyMobSpawnerComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemSpawnerComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyTrialSpawnerComponent(io.lumine.mythic.api.adapters.items.components.AbstractItemTrialSpawnerComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyTrimComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemTrimComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyBlocksAttacksComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemBlocksAttacksComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyGliderComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemGliderComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyRepairableComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemRepairableComponent);
  public default io.lumine.mythic.api.adapters.AbstractItemStack applyDeathProtectionComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemDeathProtectionComponent);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack customData(java.lang.String, io.lumine.mythic.core.utils.jnbt.Tag);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack customData(io.lumine.mythic.core.utils.jnbt.CompoundTag);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack mythicItemType(java.lang.String);
  public abstract java.util.Optional<java.lang.String> getMythicItemType();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack mythicItemVersion(int);
  public abstract java.util.Optional<java.lang.Integer> getMythicItemVersion();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack preventEnchanting();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack preventRepairingWith();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack preventCraftingWith();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack preventSmithingWith();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack UUID(java.util.UUID);
  public abstract java.util.UUID getUUID();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack timestamp(long);
  public abstract long getTimestamp();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack itemModel(org.bukkit.NamespacedKey);
  public abstract org.bukkit.NamespacedKey getItemModel();
  public abstract boolean isSimilar(io.lumine.mythic.api.adapters.AbstractItemStack);
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack copy();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack applyBlockStateComponent(io.lumine.mythic.api.drops.DropMetadata, io.lumine.mythic.api.adapters.items.components.AbstractItemBlockStateComponent);
}
