Compiled from "AbstractVector.java"
public class io.lumine.mythic.api.adapters.AbstractVector implements java.lang.Cloneable {
  public io.lumine.mythic.api.adapters.AbstractVector(int, int, int);
  public io.lumine.mythic.api.adapters.AbstractVector(double, double, double);
  public io.lumine.mythic.api.adapters.AbstractVector(float, float, float);
  public io.lumine.mythic.api.adapters.AbstractVector(java.lang.String);
  public io.lumine.mythic.api.adapters.AbstractVector();
  public org.joml.Vector3f toVector3f();
  public io.lumine.mythic.api.adapters.AbstractVector add(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector subtract(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector multiply(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector multiply(int);
  public io.lumine.mythic.api.adapters.AbstractVector multiply(double);
  public io.lumine.mythic.api.adapters.AbstractVector multiply(float);
  public io.lumine.mythic.api.adapters.AbstractVector divide(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector copy(io.lumine.mythic.api.adapters.AbstractVector);
  public double length();
  public double lengthSquared();
  public double getX();
  public int getBlockX();
  public double getY();
  public int getBlockY();
  public double getZ();
  public int getBlockZ();
  public io.lumine.mythic.api.adapters.AbstractVector setX(int);
  public io.lumine.mythic.api.adapters.AbstractVector setX(double);
  public io.lumine.mythic.api.adapters.AbstractVector setX(float);
  public io.lumine.mythic.api.adapters.AbstractVector setY(int);
  public io.lumine.mythic.api.adapters.AbstractVector setY(double);
  public io.lumine.mythic.api.adapters.AbstractVector setY(float);
  public io.lumine.mythic.api.adapters.AbstractVector setZ(int);
  public io.lumine.mythic.api.adapters.AbstractVector setZ(double);
  public io.lumine.mythic.api.adapters.AbstractVector setZ(float);
  public io.lumine.mythic.api.adapters.AbstractVector normalize();
  public io.lumine.mythic.api.adapters.AbstractVector crossProduct(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector rotate(double);
  public void rotate(io.lumine.mythic.api.adapters.AbstractVector, double);
  public void rotate(io.lumine.mythic.api.adapters.AbstractVector);
  public boolean equals(java.lang.Object);
  public int hashCode();
  public io.lumine.mythic.api.adapters.AbstractVector clone();
  public java.lang.String toString();
  public io.lumine.mythic.api.adapters.AbstractLocation toLocation(io.lumine.mythic.api.adapters.AbstractWorld);
  public io.lumine.mythic.api.adapters.AbstractLocation toLocation(io.lumine.mythic.api.adapters.AbstractWorld, float, float);
  public static double getEpsilon();
  public double dot(io.lumine.mythic.api.adapters.AbstractVector);
  public float angle(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractVector rotateAroundX(double);
  public io.lumine.mythic.api.adapters.AbstractVector rotateAroundY(double);
  public io.lumine.mythic.api.adapters.AbstractVector rotateAroundZ(double);
  public io.lumine.mythic.api.adapters.AbstractVector rotateAroundAxis(io.lumine.mythic.api.adapters.AbstractVector, double) throws java.lang.IllegalArgumentException;
  public io.lumine.mythic.api.adapters.AbstractVector rotateAroundNonUnitAxis(io.lumine.mythic.api.adapters.AbstractVector, double) throws java.lang.IllegalArgumentException;
  public boolean isNormalized();
  public boolean isFinite();
  public java.lang.Object clone() throws java.lang.CloneNotSupportedException;
}
