Compiled from "VolatileEntityHandler.java"
public interface io.lumine.mythic.api.volatilecode.handlers.VolatileEntityHandler {
  public default boolean hasDefaultAttributes(org.bukkit.entity.EntityType);
  public default io.lumine.mythic.bukkit.adapters.attributes.BukkitAttributable getDefaultAttributes(org.bukkit.entity.EntityType);
  public abstract io.lumine.mythic.api.adapters.AbstractEntity addNBTData(io.lumine.mythic.api.adapters.AbstractEntity, java.lang.String, io.lumine.mythic.core.utils.jnbt.Tag);
  public abstract io.lumine.mythic.core.utils.jnbt.CompoundTag getNBTData(io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract io.lumine.mythic.api.adapters.AbstractEntity setNBTData(io.lumine.mythic.api.adapters.AbstractEntity, io.lumine.mythic.core.utils.jnbt.CompoundTag);
  public abstract boolean isEntityInMotion(io.lumine.mythic.api.adapters.AbstractEntity, boolean);
  public default io.lumine.mythic.api.adapters.AbstractVector getEntityMotion(io.lumine.mythic.api.adapters.AbstractEntity);
  public default void setLocation(io.lumine.mythic.api.adapters.AbstractEntity, io.lumine.mythic.api.adapters.AbstractLocation);
  public default void setLocation(io.lumine.mythic.api.adapters.AbstractEntity, double, double, double, float, float);
  public abstract void setLocation(io.lumine.mythic.api.adapters.AbstractEntity, double, double, double, float, float, boolean, boolean);
  public default void setPlayerRotation(io.lumine.mythic.api.adapters.AbstractPlayer, float, float, boolean);
  public default void setHitBox(io.lumine.mythic.api.adapters.AbstractEntity, double, double);
  public default void setItemPosition(io.lumine.mythic.api.adapters.AbstractEntity, io.lumine.mythic.api.adapters.AbstractLocation);
  public default void sendEntityTeleportPacket(io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract void setEntityRotation(io.lumine.mythic.api.adapters.AbstractEntity, float, float);
  public abstract void setArmorStandNoGravity(io.lumine.mythic.api.adapters.AbstractEntity);
  public default void sendGameStateChange(io.lumine.mythic.api.adapters.AbstractPlayer, int, int);
  public default void forcePlayCredits(io.lumine.mythic.api.adapters.AbstractPlayer, float);
  public default void forceCloseWindow(io.lumine.mythic.api.adapters.AbstractPlayer);
  public default void setPlayerWorldBorder(io.lumine.mythic.api.adapters.AbstractPlayer, io.lumine.mythic.api.adapters.AbstractLocation, int);
  public abstract float getEntityAbsorptionHearts(io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract void setEntityAbsorptionHearts(io.lumine.mythic.api.adapters.AbstractEntity, float);
  public abstract void sendPlayerFakeInventoryItem(io.lumine.mythic.api.adapters.AbstractPlayer, org.bukkit.inventory.ItemStack, int);
  public default void setEntityPitch(io.lumine.mythic.api.adapters.AbstractEntity, float);
  public abstract void sendActionBarMessageToPlayer(io.lumine.mythic.api.adapters.AbstractPlayer, java.lang.String);
  public default void playTotemEffect(io.lumine.mythic.api.adapters.AbstractPlayer, org.bukkit.inventory.ItemStack);
  public abstract void setEntitySpawnReason(io.lumine.mythic.api.adapters.AbstractEntity, org.bukkit.event.entity.CreatureSpawnEvent$SpawnReason);
  public default void playTotemEffect(io.lumine.mythic.api.adapters.AbstractPlayer, int);
  public abstract void setEntityPose(io.lumine.mythic.api.adapters.AbstractEntity, java.lang.String);
  public abstract double getPassengerRidingOffset(io.lumine.mythic.api.adapters.AbstractEntity);
  public default float getPassengerRidingOffset(io.lumine.mythic.api.adapters.AbstractEntity, io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract java.util.Collection<io.lumine.mythic.api.adapters.AbstractPlayer> getTrackedPlayers(io.lumine.mythic.api.adapters.AbstractEntity);
  public default float getItemGroupCooldownPercent(io.lumine.mythic.api.adapters.AbstractPlayer, java.lang.String);
  public default void setItemGroupCooldown(io.lumine.mythic.api.adapters.AbstractPlayer, java.lang.String, int);
  public default void removeItemGroupCooldown(io.lumine.mythic.api.adapters.AbstractPlayer, java.lang.String);
  public abstract void spawnFakeLightning(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public default void playFreezeEffect(io.lumine.mythic.api.adapters.AbstractPlayer, int);
  public default void playEntityAnimation(io.lumine.mythic.api.adapters.AbstractEntity, byte, java.util.Collection<io.lumine.mythic.api.adapters.AbstractPlayer>);
  public abstract int getNextEntityId();
  public default void setCustomName(io.lumine.mythic.api.adapters.AbstractEntity, java.lang.String);
  public default boolean doDamage(io.lumine.mythic.api.skills.damage.DamageMetadata, io.lumine.mythic.api.adapters.AbstractEntity);
  public default void registerAttribute(io.lumine.mythic.api.adapters.AbstractEntity, org.bukkit.attribute.Attribute);
  public default void stopUsingItem(io.lumine.mythic.api.adapters.AbstractEntity);
  public default void setGlowing(io.lumine.mythic.api.adapters.AbstractEntity, boolean, io.lumine.mythic.api.adapters.AbstractPlayer);
  public default void setGlowColor(io.lumine.mythic.api.adapters.AbstractEntity, io.lumine.mythic.core.glow.GlowColor, io.lumine.mythic.api.adapters.AbstractPlayer);
  public default void initTeams(io.lumine.mythic.api.adapters.AbstractPlayer);
  public default boolean isUsingSpyglass(io.lumine.mythic.api.adapters.AbstractPlayer);
}
