Compiled from "SkillMetadata.java"
public interface io.lumine.mythic.api.skills.SkillMetadata extends io.lumine.mythic.core.skills.placeholders.PlaceholderMeta,io.lumine.mythic.core.skills.variables.VariableHolder {
  public abstract io.lumine.mythic.api.skills.SkillTrigger getCause();
  public abstract io.lumine.mythic.api.skills.SkillCaster getCaster();
  public abstract io.lumine.mythic.api.adapters.AbstractItemStack getCasterItem();
  public abstract io.lumine.mythic.api.adapters.AbstractEntity getTrigger();
  public abstract io.lumine.mythic.api.adapters.AbstractLocation getOrigin();
  public abstract java.util.Map<java.lang.String, java.lang.String> getParameters();
  public abstract io.lumine.mythic.core.skills.variables.VariableRegistry getVariables();
  public abstract float getPower();
  public abstract void setPower(float);
  public abstract boolean getExecuteAfterDeath();
  public abstract void setExecuteAfterDeath(boolean);
  public abstract boolean isParentCancelled();
  public abstract boolean isAsync();
  public abstract io.lumine.mythic.api.skills.SkillMetadata setOrigin(io.lumine.mythic.api.adapters.AbstractLocation);
  public abstract boolean getIsAsync();
  public abstract io.lumine.mythic.api.skills.SkillMetadata setIsAsync(boolean);
  public abstract io.lumine.mythic.api.skills.IParentSkill getCallingEvent();
  public abstract void setCallingEvent(io.lumine.mythic.api.skills.IParentSkill);
  public abstract void cancelEvent();
  public abstract boolean hasEntityTargets();
  public abstract java.util.Collection<io.lumine.mythic.api.adapters.AbstractEntity> getEntityTargets();
  public abstract io.lumine.mythic.api.skills.SkillMetadata setEntityTargets(java.util.Collection<io.lumine.mythic.api.adapters.AbstractEntity>);
  public abstract io.lumine.mythic.api.skills.SkillMetadata setEntityTarget(io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract boolean hasLocationTargets();
  public abstract java.util.Collection<io.lumine.mythic.api.adapters.AbstractLocation> getLocationTargets();
  public abstract io.lumine.mythic.api.skills.SkillMetadata setLocationTargets(java.util.Collection<io.lumine.mythic.api.adapters.AbstractLocation>);
  public abstract io.lumine.mythic.api.skills.SkillMetadata setLocationTarget(io.lumine.mythic.api.adapters.AbstractLocation);
  public abstract void setConsoleTarget(boolean);
  public abstract boolean isConsoleTarget();
  public abstract boolean hasTarget();
  public abstract io.lumine.mythic.api.skills.SkillMetadata setMetadata(java.lang.String, java.lang.Object);
  public abstract java.util.Optional<java.lang.Object> getMetadata(java.lang.String);
  public abstract <T> java.util.Optional<T> getMetadata(java.lang.Class<T>, java.lang.String);
  public abstract java.util.Optional<java.lang.Object> removeMetadata(java.lang.String);
  public abstract <T> java.util.Optional<T> removeMetadata(java.lang.Class<T>, java.lang.String);
  public abstract void clearMetadata();
  public abstract void snapshotCasterStats();
  public abstract java.util.Optional<io.lumine.mythic.api.skills.stats.StatSnapshot> getCasterStats();
  public abstract java.util.Optional<io.lumine.mythic.api.skills.stats.StatSnapshot> getTriggerStats();
  public abstract io.lumine.mythic.api.skills.SkillMetadata deepClone();
  public abstract io.lumine.mythic.core.skills.SkillMetadataImpl deeperClone();
  public abstract io.lumine.mythic.api.skills.SkillMetadata deepClone(boolean);
  public abstract io.lumine.mythic.core.skills.SkillMetadataImpl deeperClone(boolean);
  public abstract void setCaster(io.lumine.mythic.api.skills.SkillCaster);
  public abstract void setTrigger(io.lumine.mythic.api.adapters.AbstractEntity);
  public abstract io.lumine.mythic.core.skills.triggers.SkillTriggerMetadata getTriggerMetadata();
  public abstract void setTerminatedReference(java.util.concurrent.atomic.AtomicBoolean);
  public abstract void terminate();
  public abstract boolean isTerminated();
  public default io.lumine.mythic.core.skills.placeholders.PlaceholderMeta setMetadata(java.lang.String, java.lang.Object);
}
