Compiled from "MythicConfig.java"
public interface io.lumine.mythic.api.config.MythicConfig {
  public static io.lumine.mythic.api.config.MythicConfig of(java.io.File);
  public abstract java.io.File getFile();
  public abstract void setKey(java.lang.String);
  public abstract java.lang.String getKey();
  public abstract boolean isSet(java.lang.String);
  public abstract java.lang.String determineWhichKeyToUse(java.lang.String, java.lang.String...);
  public abstract void set(java.lang.String, java.lang.Object);
  public abstract void setSave(java.lang.String, java.lang.Object);
  public abstract void load();
  public abstract void save();
  public abstract io.lumine.mythic.api.config.MythicConfig getNestedConfig(java.lang.String);
  public abstract java.util.Map<java.lang.String, io.lumine.mythic.api.config.MythicConfig> getNestedConfigs(java.lang.String);
  public abstract boolean isMapList(java.lang.String);
  public abstract boolean isDouble(java.lang.String);
  public abstract boolean isLong(java.lang.String);
  public abstract boolean isString(java.lang.String);
  public abstract java.lang.String getString(java.lang.String);
  public abstract java.lang.String getString(java.lang.String[]);
  public abstract java.lang.String getString(java.lang.String, java.lang.String);
  public abstract java.lang.String getString(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract java.lang.String getNamespacedString(java.lang.String);
  public abstract java.lang.String getNamespacedString(java.lang.String[]);
  public abstract java.lang.String getNamespacedString(java.lang.String, java.lang.String);
  public abstract java.lang.String getNamespacedString(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract <T extends java.lang.Enum> T getEnum(java.lang.String, java.lang.Class<T>, T);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String, io.lumine.mythic.bukkit.utils.serialize.Chroma);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String[]);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String[], java.lang.String);
  public abstract java.lang.String getColorString(java.lang.String);
  public abstract java.lang.String getColorString(java.lang.String, java.lang.String);
  public abstract boolean getBoolean(java.lang.String);
  public abstract boolean getBoolean(java.lang.String, boolean);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String[]);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String, java.lang.Boolean);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String[], java.lang.Boolean);
  public abstract int getInteger(java.lang.String);
  public abstract int getInteger(java.lang.String, int);
  public abstract int getInteger(java.lang.String[], int);
  public abstract int getInt(java.lang.String);
  public abstract int getInt(java.lang.String, int);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderAngle getPlaceholderAngle(java.lang.String, io.lumine.mythic.bukkit.utils.numbers.AngleUnit);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderAngle getPlaceholderAngle(java.lang.String, io.lumine.mythic.bukkit.utils.numbers.AngleUnit, java.lang.String);
  public abstract double getDouble(java.lang.String);
  public abstract double getDouble(java.lang.String, double);
  public abstract float getFloat(java.lang.String);
  public abstract float getFloat(java.lang.String, float);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Percent getPercent(java.lang.String);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Percent getPercent(java.lang.String, io.lumine.mythic.bukkit.utils.serialize.Percent);
  public abstract java.util.List<java.lang.String> getStringList(java.lang.String);
  public abstract java.util.List<java.lang.String> getStringList(java.lang.String, java.util.List<java.lang.String>);
  public abstract java.util.List<java.lang.String> getColorStringList(java.lang.String);
  public abstract java.util.List<io.lumine.mythic.api.skills.placeholders.PlaceholderString> getPlaceholderStringList(java.lang.String);
  public abstract java.util.List<io.lumine.mythic.api.skills.placeholders.PlaceholderString> getPlaceholderStringList(java.lang.String, java.util.List<java.lang.String>);
  public abstract java.util.List<io.lumine.mythic.api.skills.placeholders.PlaceholderString> getPlaceholderStringListAlt(java.lang.String, java.util.List<io.lumine.mythic.api.skills.placeholders.PlaceholderString>);
  public abstract io.lumine.mythic.core.skills.placeholders.parsers.PlaceholderColorImpl getPlaceholderColor(java.lang.String, java.lang.String);
  public abstract java.util.List<java.util.Map<?, ?>> getMapList(java.lang.String);
  public abstract java.util.List<io.lumine.mythic.api.config.MythicConfig> getConfigurationList(java.lang.String);
  public abstract java.util.List<?> getList(java.lang.String);
  public abstract java.util.List<java.lang.Byte> getByteList(java.lang.String);
  public abstract org.bukkit.inventory.ItemStack getItemStack(java.lang.String, java.lang.String);
  public abstract boolean isConfigurationSection(java.lang.String);
  public abstract java.util.Set<java.lang.String> getKeys();
  public abstract java.util.Set<java.lang.String> getKeys(java.lang.String);
  public abstract boolean contains(java.lang.String);
  public abstract boolean isBoolean(java.lang.String);
  public abstract boolean isInt(java.lang.String);
  public abstract boolean isList(java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInt(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInt(java.lang.String[], java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInt(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderLong getPlaceholderLong(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderLong getPlaceholderLong(java.lang.String[], java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract void merge(io.lumine.mythic.api.config.MythicConfig, java.util.List<java.lang.String>);
  public abstract org.bukkit.configuration.ConfigurationSection getRootConfiguration();
  public abstract void unset(java.lang.String);
  public abstract void unsetSave(java.lang.String);
  public abstract void deleteNodeAndSave();
  public abstract java.lang.String getFileName();
}
