Compiled from "MythicLineConfig.java"
public interface io.lumine.mythic.api.config.MythicLineConfig {
  public abstract boolean getBoolean(java.lang.String);
  public abstract boolean getBoolean(java.lang.String, boolean);
  public abstract boolean getBoolean(java.lang.String[], boolean);
  public abstract java.lang.Boolean getBooleanNullable(java.lang.String);
  public abstract java.lang.Boolean getBooleanNullable(java.lang.String[]);
  public abstract java.lang.String getString(java.lang.String);
  public abstract java.lang.String getString(java.lang.String, java.lang.String);
  public abstract java.lang.String getString(java.lang.String[]);
  public abstract java.lang.String getString(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String[]);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String, java.lang.Boolean);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderBoolean getPlaceholderBoolean(java.lang.String[], java.lang.Boolean);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String, io.lumine.mythic.bukkit.utils.serialize.Chroma);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String[]);
  public abstract io.lumine.mythic.bukkit.utils.serialize.Chroma getColor(java.lang.String[], io.lumine.mythic.bukkit.utils.serialize.Chroma);
  public abstract java.util.List<java.lang.String> parseStringList(java.lang.String);
  public abstract java.util.List<java.lang.String> getStringList(java.lang.String, java.lang.String);
  public abstract java.util.List<java.lang.String> getStringList(java.lang.String[], java.lang.String);
  public abstract java.util.List<java.lang.String> getStringList(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract int getInteger(java.lang.String);
  public abstract int getInteger(java.lang.String, int);
  public abstract int getInteger(java.lang.String[]);
  public abstract int getInteger(java.lang.String[], int);
  public abstract double getDouble(java.lang.String);
  public abstract double getDouble(java.lang.String, double);
  public abstract double getDouble(java.lang.String[], double);
  public abstract float getFloat(java.lang.String);
  public abstract float getFloat(java.lang.String, float);
  public abstract float getFloat(java.lang.String[], float);
  public abstract long getLong(java.lang.String[], long);
  public abstract java.util.List<io.lumine.mythic.bukkit.utils.serialize.Locus> getLocationList(java.lang.String[], java.util.List<io.lumine.mythic.bukkit.utils.serialize.Locus>);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderString getPlaceholderString(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String, io.lumine.mythic.api.skills.placeholders.PlaceholderInt);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String[], io.lumine.mythic.api.skills.placeholders.PlaceholderInt, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String, int);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderInt getPlaceholderInteger(java.lang.String[], int, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String, double);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String[], double, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String, io.lumine.mythic.api.skills.placeholders.PlaceholderDouble);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderDouble getPlaceholderDouble(java.lang.String[], io.lumine.mythic.api.skills.placeholders.PlaceholderDouble, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderFloat getPlaceholderFloat(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderFloat getPlaceholderFloat(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderFloat getPlaceholderFloat(java.lang.String, float);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderFloat getPlaceholderFloat(java.lang.String[], float, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderColor getPlaceholderColor(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderColor getPlaceholderColor(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderVector getPlaceholderVector(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderVector getPlaceholderVector(java.lang.String[], java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderVector getPlaceholderVector(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderAngle getPlaceholderAngle(java.lang.String[], io.lumine.mythic.bukkit.utils.numbers.AngleUnit, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PlaceholderAngle getPlaceholderAngle(java.lang.String[], io.lumine.mythic.bukkit.utils.numbers.AngleUnit, java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.core.skills.SkillAudience getAudience(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.core.skills.SkillAudience getAudience(java.lang.String[], java.lang.String, java.lang.String...);
  public abstract io.lumine.mythic.api.skills.placeholders.PolymorphicPlaceholder getPolymorphicPlaceholder(java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PolymorphicPlaceholder getPolymorphicPlaceholder(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.api.skills.placeholders.PolymorphicPlaceholder getPolymorphicPlaceholder(java.lang.String[]);
  public abstract io.lumine.mythic.api.skills.placeholders.PolymorphicPlaceholder getPolymorphicPlaceholder(java.lang.String[], java.lang.String);
  public abstract io.lumine.mythic.core.skills.variables.VariableScopedName getVariableScopedName(java.lang.String);
  public abstract io.lumine.mythic.core.skills.variables.VariableScopedName getVariableScopedName(java.lang.String, java.lang.String);
  public abstract io.lumine.mythic.core.skills.variables.VariableScopedName getVariableScopedName(java.lang.String[]);
  public abstract io.lumine.mythic.core.skills.variables.VariableScopedName getVariableScopedName(java.lang.String[], java.lang.String);
  public abstract <T extends java.lang.Enum<T>> T getEnum(java.lang.String[], java.lang.Class<T>, T);
  public abstract <T extends java.lang.Enum<T>> T getEnum(java.lang.String[], java.lang.Class<T>, T, java.lang.String);
  public abstract java.lang.String getKey();
  public abstract java.lang.String getLine();
  public abstract java.lang.String getFileName();
  public abstract java.util.Set<java.util.Map$Entry<java.lang.String, java.lang.String>> entrySet();
}
