Compiled from "AbstractLocation.java"
public class io.lumine.mythic.api.adapters.AbstractLocation implements java.lang.Cloneable {
  public static io.lumine.mythic.api.adapters.AbstractLocation deserialize(java.lang.String);
  public static io.lumine.mythic.api.adapters.AbstractLocation deserializeFromVariableLocation(java.lang.String);
  public static io.lumine.mythic.api.adapters.AbstractLocation from(org.joml.Vector3dc, float, float);
  public io.lumine.mythic.api.adapters.AbstractLocation();
  public io.lumine.mythic.api.adapters.AbstractLocation(double, double, double);
  public io.lumine.mythic.api.adapters.AbstractLocation(java.lang.String, double, double, double);
  public io.lumine.mythic.api.adapters.AbstractLocation(io.lumine.mythic.api.adapters.AbstractWorld, double, double, double);
  public io.lumine.mythic.api.adapters.AbstractLocation(io.lumine.mythic.api.adapters.AbstractWorld, double, double, double, float, float);
  public io.lumine.mythic.api.adapters.AbstractLocation(io.lumine.mythic.bukkit.utils.serialize.Position);
  public io.lumine.mythic.bukkit.utils.serialize.Position toPosition();
  public io.lumine.mythic.bukkit.utils.serialize.Locus toLocus();
  public io.lumine.mythic.bukkit.utils.serialize.Point toPoint();
  public io.lumine.mythic.api.adapters.AbstractLocation block();
  public io.lumine.mythic.api.adapters.AbstractLocation center();
  public void setX(double);
  public double getX();
  public void setY(double);
  public double getY();
  public void setZ(double);
  public double getZ();
  public int getBlockX();
  public int getBlockY();
  public int getBlockZ();
  public int getChunkX();
  public int getChunkZ();
  public double getCenterX();
  public double getCenterY();
  public double getCenterZ();
  public void setPosition(org.joml.Vector3dc);
  public float getYaw();
  public void setYaw(float);
  public float getPitch();
  public void setPitch(float);
  public io.lumine.mythic.api.adapters.AbstractWorld getWorld();
  public double distance(io.lumine.mythic.api.adapters.AbstractLocation) throws java.lang.IllegalArgumentException;
  public double distanceSquared(io.lumine.mythic.api.adapters.AbstractLocation) throws java.lang.IllegalArgumentException;
  public double distanceSquared(io.lumine.mythic.api.adapters.AbstractEntity);
  public double distance2D(io.lumine.mythic.api.adapters.AbstractLocation);
  public double distance2DSquared(io.lumine.mythic.api.adapters.AbstractLocation);
  public boolean distanceLessThan(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceLessThanSquared(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceLessOrEq(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceLessOrEqSquared(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceGreaterThan(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceGreaterThanSquared(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceGreaterOrEq(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public boolean distanceGreaterOrEqSquared(io.lumine.mythic.api.adapters.AbstractLocation, double);
  public io.lumine.mythic.api.adapters.AbstractLocation add(double, double, double);
  public io.lumine.mythic.api.adapters.AbstractVector getDirection();
  public io.lumine.mythic.api.adapters.AbstractLocation setDirection(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractLocation add(io.lumine.mythic.api.adapters.AbstractLocation);
  public io.lumine.mythic.api.adapters.AbstractLocation add(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractLocation subtract(double, double, double);
  public io.lumine.mythic.api.adapters.AbstractLocation subtract(io.lumine.mythic.api.adapters.AbstractLocation);
  public io.lumine.mythic.api.adapters.AbstractLocation subtract(io.lumine.mythic.api.adapters.AbstractVector);
  public io.lumine.mythic.api.adapters.AbstractLocation multiply(double);
  public io.lumine.mythic.api.adapters.AbstractLocation interpolate(io.lumine.mythic.api.adapters.AbstractLocation, int);
  public io.lumine.mythic.api.adapters.AbstractLocation zero();
  public io.lumine.mythic.api.adapters.AbstractVector toVector();
  public org.joml.Vector3dc toVector3d();
  public io.lumine.mythic.api.adapters.AbstractLocation getRelative(io.lumine.mythic.api.adapters.AbstractDirection);
  public io.lumine.mythic.api.adapters.AbstractLocation getRelative(io.lumine.mythic.api.adapters.AbstractDirection, int);
  public boolean equals(java.lang.Object);
  public java.lang.String serializeShortForm();
  public java.lang.String toString();
  public int hashCode();
  public io.lumine.mythic.api.adapters.AbstractLocation clone();
  public boolean isLoaded();
  public io.lumine.mythic.api.adapters.AbstractBiome getBiome();
  public boolean isFinite();
  public io.lumine.mythic.api.adapters.AbstractBlock getBlock();
  public java.lang.Object clone() throws java.lang.CloneNotSupportedException;
}
